restriction_enzymes = {
    'AatII': {'sequence': 'GACGTC', 'cut': 5, 'end_type': 'sticky', 'overhang': 5},
    'Acc65I': {'sequence': 'GGTACC', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'AccI': {'sequence': 'GTMKAC', 'cut': 2, 'end_type': 'sticky', 'overhang': 2},
    'AciI': {'sequence': 'CCGC', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'AclI': {'sequence': 'AACGTT', 'cut': 2, 'end_type': 'sticky', 'overhang': 2},
    'AcuI': {'sequence': 'CTGAAGNNNNNNNNNNNNNNNN', 'cut': 22, 'end_type': 'sticky', 'overhang': 2},
    'AflII': {'sequence': 'CTTAAG', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'AflIII': {'sequence': 'ACRYGT', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'AgeI-HF': {'sequence': 'ACCGGT', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'AhdI': {'sequence': 'GACNNNNNGTC', 'cut': 6, 'end_type': 'sticky', 'overhang': 6},
    'AlwI': {'sequence': 'GGATCNNNNN', 'cut': 9, 'end_type': 'sticky', 'overhang': 0},
    'AlwNI': {'sequence': 'CAGNNNCTG', 'cut': 6, 'end_type': 'sticky', 'overhang': 6},
    'ApaI': {'sequence': 'GGGCCC', 'cut': 5, 'end_type': 'sticky', 'overhang': 5},
    'ApaLI': {'sequence': 'GTGCAC', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'ApeKI': {'sequence': 'GCWGC', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'ApoI-HF': {'sequence': 'RAATTY', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'AscI': {'sequence': 'GGCGCGCC', 'cut': 2, 'end_type': 'sticky', 'overhang': 2},
    'AseI': {'sequence': 'ATTAAT', 'cut': 2, 'end_type': 'sticky', 'overhang': 2},
    'AsiSI': {'sequence': 'GCGATCGC', 'cut': 5, 'end_type': 'sticky', 'overhang': 5},
    'AvaI': {'sequence': 'CYCGRG', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'AvaII': {'sequence': 'GGWCC', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'AvrII': {'sequence': 'CCTAGG', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'AdeI': {'sequence': 'CACNNNGTG', 'cut': 6, 'end_type': 'sticky', 'overhang': 6},
    'AasI': {'sequence': 'GACNNNNNNGTC', 'cut': 7, 'end_type': 'sticky', 'overhang': 7},
    'BaeGI': {'sequence': 'GKGCMC', 'cut': 5, 'end_type': 'sticky', 'overhang': 5},
    'BamHI': {'sequence': 'GGATCC', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'BanI': {'sequence': 'GGYRCC', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'BanII': {'sequence': 'GRGCYC', 'cut': 5, 'end_type': 'sticky', 'overhang': 5},
    'BbsI': {'sequence': 'GAAGACNNNNNN', 'cut': 8, 'end_type': 'sticky', 'overhang': 0},
    'BbvCI': {'sequence': 'CCTCAGC', 'cut': 2, 'end_type': 'sticky', 'overhang': 2},
    'BbvI': {'sequence': 'GCAGCNNNNNNNNNNNN', 'cut': 13, 'end_type': 'sticky', 'overhang': 0},
    'BccI': {'sequence': 'CCATCNNNNN', 'cut': 9, 'end_type': 'sticky', 'overhang': 0},
    'BceAI': {'sequence': 'ACGGCNNNNNNNNNNNNNN', 'cut': 17, 'end_type': 'sticky', 'overhang': 0},
    'BciVI': {'sequence': 'GTATCCNNNNNN', 'cut': 12, 'end_type': 'sticky', 'overhang': 1},
    'BclI': {'sequence': 'TGATCA', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'BcoDI': {'sequence': 'GTCTCNNNNN', 'cut': 6, 'end_type': 'sticky', 'overhang': 0},
    'BfaI': {'sequence': 'CTAG', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'BfuAI': {'sequence': 'ACCTGCNNNNNNNN', 'cut': 10, 'end_type': 'sticky', 'overhang': 0},
    'BglI': {'sequence': 'GCCNNNNNGGC', 'cut': 7, 'end_type': 'sticky', 'overhang': 7},
    'BglII': {'sequence': 'AGATCT', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'BlpI': {'sequence': 'GCTNAGC', 'cut': 2, 'end_type': 'sticky', 'overhang': 2},
    'BmrI': {'sequence': 'ACTGGGNNNNN', 'cut': 11, 'end_type': 'sticky', 'overhang': 1},
    'BpmI': {'sequence': 'CTGGAGNNNNNNNNNNNNNNNN', 'cut': 22, 'end_type': 'sticky', 'overhang': 2},
    'Bpu10I': {'sequence': 'CCTNAGC', 'cut': 2, 'end_type': 'sticky', 'overhang': 2},
    'BpuEI': {'sequence': 'CTTGAGNNNNNNNNNNNNNNNN', 'cut': 22, 'end_type': 'sticky', 'overhang': 2},
    'BsaHI': {'sequence': 'GRCCYC', 'cut': 2, 'end_type': 'sticky', 'overhang': 2},
    'BsaI-HFv2': {'sequence': 'GGTCTCNNNNN', 'cut': 7, 'end_type': 'sticky', 'overhang': 0},
    'BsaJI': {'sequence': 'CCNNGG', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'BsaWI': {'sequence': 'WCCGGW', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'BseRI': {'sequence': 'GAGGAGNNNNNNNNNN', 'cut': 16, 'end_type': 'sticky', 'overhang': 2},
    'BseYI': {'sequence': 'CCCAGC', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'BsgI': {'sequence': 'GTGCAGNNNNNNNNNNNNNNNN', 'cut': 22, 'end_type': 'sticky', 'overhang': 2},
    'BsiEI': {'sequence': 'CGRYCG', 'cut': 4, 'end_type': 'sticky', 'overhang': 4},
    'BsiHKAI': {'sequence': 'GWGCWC', 'cut': 5, 'end_type': 'sticky', 'overhang': 5},
    'BsiWI': {'sequence': 'CGTACG', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'BslI': {'sequence': 'CCNNNNNNNGG', 'cut': 7, 'end_type': 'sticky', 'overhang': 7},
    'BsmAI': {'sequence': 'GTCTCNNNNN', 'cut': 6, 'end_type': 'sticky', 'overhang': 0},
    'BsmBI-v2': {'sequence': 'CGTCTCNNNNN', 'cut': 7, 'end_type': 'sticky', 'overhang': 0},
    'BsmFI': {'sequence': 'GGGACNNNNNNNNNNNNNN', 'cut': 15, 'end_type': 'sticky', 'overhang': 0},
    'BsmI': {'sequence': 'GAATGCN', 'cut': 7, 'end_type': 'sticky', 'overhang': 2},
    'BsoBI': {'sequence': 'CYCGRG', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'Bsp1286I': {'sequence': 'GDGCHC', 'cut': 5, 'end_type': 'sticky', 'overhang': 5},
    'BspDI': {'sequence': 'ATCGAT', 'cut': 2, 'end_type': 'sticky', 'overhang': 2},
    'BspEI': {'sequence': 'TCCGGA', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'BspHI': {'sequence': 'TCATGA', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'BspMI': {'sequence': 'ACCTGCNNNNNNNN', 'cut': 10, 'end_type': 'sticky', 'overhang': 0},
    'BspQI': {'sequence': 'GCTCTTCNNNN', 'cut': 8, 'end_type': 'sticky', 'overhang': 0},
    'BsrDI': {'sequence': 'GCAATGNN', 'cut': 8, 'end_type': 'sticky', 'overhang': 2},
    'BsrFI-v2': {'sequence': 'RCCGGY', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'BsrGI-HF': {'sequence': 'TGTACA', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'BsrI': {'sequence': 'ACTGGN', 'cut': 6, 'end_type': 'sticky', 'overhang': 2},
    'BssHII': {'sequence': 'GCGCGC', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'BssSI-v2': {'sequence': 'CACGAG', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'BstAPI': {'sequence': 'GCANNNNNTGC', 'cut': 7, 'end_type': 'sticky', 'overhang': 7},
    'BstBI': {'sequence': 'TTCGAA', 'cut': 2, 'end_type': 'sticky', 'overhang': 2},
    'BstEII-HF': {'sequence': 'GGTNACC', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'BstNI': {'sequence': 'CCWGG', 'cut': 2, 'end_type': 'sticky', 'overhang': 2},
    'BstXI': {'sequence': 'CCANNNNNNTGG', 'cut': 8, 'end_type': 'sticky', 'overhang': 8},
    'BstYI': {'sequence': 'RGATCY', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'Bsu36I': {'sequence': 'CCTNAGG', 'cut': 2, 'end_type': 'sticky', 'overhang': 2},
    'BtgI': {'sequence': 'CCRYGG', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'BtgZI': {'sequence': 'GCGATGNNNNNNNNNNNNNN', 'cut': 16, 'end_type': 'sticky', 'overhang': 0},
    'BtsCI': {'sequence': 'GGATGNN', 'cut': 7, 'end_type': 'sticky', 'overhang': 2},
    'BtsIMutI': {'sequence': 'CAGTGNN', 'cut': 7, 'end_type': 'sticky', 'overhang': 2},
    'BtsI-v2': {'sequence': 'GCAGTGNN', 'cut': 8, 'end_type': 'sticky', 'overhang': 2},
    'Bpu10I': {'sequence': 'CCTNAGC', 'cut': 2, 'end_type': 'sticky', 'overhang': 2},
    'BseSI': {'sequence': 'GKGCMC', 'cut': 5, 'end_type': 'sticky', 'overhang': 5},
    'BspOI': {'sequence': 'GCCTAGC', 'cut': 5, 'end_type': 'sticky', 'overhang': 5},
    'BfoI': {'sequence': 'RGCGCY', 'cut': 5, 'end_type': 'sticky', 'overhang': 5},
    'ClaI': {'sequence': 'ATCGAT', 'cut': 2, 'end_type': 'sticky', 'overhang': 2},
    'CviQI': {'sequence': 'GTAC', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'CpoI': {'sequence': 'CGGWCC', 'cut': 2, 'end_type': 'sticky', 'overhang': 2},
    'CsiI': {'sequence': 'ACCWGGT', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'DdeI': {'sequence': 'CTNAG', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'DpnII': {'sequence': 'GATC', 'cut': 0, 'end_type': 'sticky', 'overhang': 0},
    'DrdI': {'sequence': 'GACNNNNNNGTC', 'cut': 7, 'end_type': 'sticky', 'overhang': 7},
    'EaeI': {'sequence': 'YGGCCR', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'EagI-HF': {'sequence': 'CGGCCG', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'EarI': {'sequence': 'CTCTTCNNNN', 'cut': 7, 'end_type': 'sticky', 'overhang': 0},
    'EciI': {'sequence': 'GGCGGANNNNNNNNNNN', 'cut': 17, 'end_type': 'sticky', 'overhang': 2},
    'EcoNI': {'sequence': 'CCTNNNNNAGG', 'cut': 5, 'end_type': 'sticky', 'overhang': 5},
    'EcoO109I': {'sequence': 'RGGNCCY', 'cut': 2, 'end_type': 'sticky', 'overhang': 2},
    'EcoP15I': {'sequence': 'CAGCAGNNNNNNNNNNNNNNNNNNNNNNNNNNN', 'cut': 31, 'end_type': 'sticky', 'overhang': 0},
    'EcoRI': {'sequence': 'GAATTC', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'Esp3I': {'sequence': 'CGTCTCNNNNN', 'cut': 7, 'end_type': 'sticky', 'overhang': 0},
    'Eco57I': {'sequence': 'CTGAAGNNNNNNNNNNNNNNNN', 'cut': 22, 'end_type': 'sticky', 'overhang': 2},
    'FatI': {'sequence': 'CATG', 'cut': 0, 'end_type': 'sticky', 'overhang': 0},
    'FauI': {'sequence': 'CCCGCNNNNNN', 'cut': 9, 'end_type': 'sticky', 'overhang': 0},
    'Fnu4HI': {'sequence': 'GCNGC', 'cut': 2, 'end_type': 'sticky', 'overhang': 2},
    'FokI': {'sequence': 'GGATGNNNNNNNNNNNNN', 'cut': 14, 'end_type': 'sticky', 'overhang': 0},
    'FseI': {'sequence': 'GGCCGGCC', 'cut': 6, 'end_type': 'sticky', 'overhang': 6},
    'HaeII': {'sequence': 'RGCGCY', 'cut': 5, 'end_type': 'sticky', 'overhang': 5},
    'HgaI': {'sequence': 'GACGCNNNNNNNNNN', 'cut': 10, 'end_type': 'sticky', 'overhang': 0},
    'HhaI': {'sequence': 'GCGC', 'cut': 3, 'end_type': 'sticky', 'overhang': 3},
    'HindIII': {'sequence': 'AAGCTT', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'HinfI': {'sequence': 'GANTC', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'HinP1I': {'sequence': 'GCGC', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'HpaII': {'sequence': 'CCGG', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'HphI': {'sequence': 'GGTGANNNNNNNN', 'cut': 13, 'end_type': 'sticky', 'overhang': 1},
    'Hpy188I': {'sequence': 'TCNGA', 'cut': 3, 'end_type': 'sticky', 'overhang': 3},
    'Hpy188III': {'sequence': 'TCNNGA', 'cut': 2, 'end_type': 'sticky', 'overhang': 2},
    'Hpy99I': {'sequence': 'CGWCG', 'cut': 5, 'end_type': 'sticky', 'overhang': 5},
    'HpyAV': {'sequence': 'CCTTCNNNNNN', 'cut': 11, 'end_type': 'sticky', 'overhang': 1},
    'HpyCH4III': {'sequence': 'ACNGT', 'cut': 3, 'end_type': 'sticky', 'overhang': 3},
    'HpyCH4IV': {'sequence': 'ACGT', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'I-CeuI': {'sequence': 'TAACTATAACGGTCCTAAGGTAGCGAA', 'cut': 18, 'end_type': 'sticky', 'overhang': 13},
    'I-SceI': {'sequence': 'TAGGGATAACAGGGTAAT', 'cut': 9, 'end_type': 'sticky', 'overhang': 13},
    'KasI': {'sequence': 'GGCGCC', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'KpnI-HF': {'sequence': 'GGTACC', 'cut': 5, 'end_type': 'sticky', 'overhang': 5},
    'MboI': {'sequence': 'GATC', 'cut': 0, 'end_type': 'sticky', 'overhang': 0},
    'MboII': {'sequence': 'GAAGANNNNNNNN', 'cut': 13, 'end_type': 'sticky', 'overhang': 1},
    'MunI': {'sequence': 'CAATTG', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'MluCI': {'sequence': 'AATT', 'cut': 0, 'end_type': 'sticky', 'overhang': 0},
    'MluI-HF': {'sequence': 'ACGCGT', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'MmeI': {'sequence': 'TCCRACNNNNNNNNNNNNNNNNNNNN', 'cut': 26, 'end_type': 'sticky', 'overhang': 2},
    'MnlI': {'sequence': 'CCTCNNNNNNN', 'cut': 11, 'end_type': 'sticky', 'overhang': 1},
    'MseI': {'sequence': 'TTAA', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'MspI': {'sequence': 'CCGG', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'MwoI': {'sequence': 'GCNNNNNNNGC', 'cut': 7, 'end_type': 'sticky', 'overhang': 7},
    'MreI': {'sequence': 'CGCCGGCG', 'cut': 2, 'end_type': 'sticky', 'overhang': 2},
    'NarI': {'sequence': 'GGCGCC', 'cut': 2, 'end_type': 'sticky', 'overhang': 2},
    'NciI': {'sequence': 'CCSGG', 'cut': 2, 'end_type': 'sticky', 'overhang': 2},
    'NcoI': {'sequence': 'CCATGG', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'NdeI': {'sequence': 'CATATG', 'cut': 2, 'end_type': 'sticky', 'overhang': 2},
    'NgoMIV': {'sequence': 'GCCGGC', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'NheI-HF': {'sequence': 'GCTAGC', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'NlaIII': {'sequence': 'CATG', 'cut': 4, 'end_type': 'sticky', 'overhang': 4},
    'NotI': {'sequence': 'GCGGCCGC', 'cut': 2, 'end_type': 'sticky', 'overhang': 2},
    'NsiI': {'sequence': 'ATGCAT', 'cut': 5, 'end_type': 'sticky', 'overhang': 5},
    'NspI': {'sequence': 'RCATGY', 'cut': 5, 'end_type': 'sticky', 'overhang': 5},
    'PacI': {'sequence': 'TTAATTAA', 'cut': 5, 'end_type': 'sticky', 'overhang': 5},
    'PaeR7I': {'sequence': 'CTCGAG', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'PaqCI': {'sequence': 'CACCTGCNNNNNNNN', 'cut': 11, 'end_type': 'sticky', 'overhang': 0},
    'PciI': {'sequence': 'ACATGT', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'PflFI': {'sequence': 'GACNNNGTC', 'cut': 4, 'end_type': 'sticky', 'overhang': 4},
    'PflMI': {'sequence': 'CCANNNNNTGG', 'cut': 7, 'end_type': 'sticky', 'overhang': 7},
    'PI-PspI': {'sequence': 'TGGCAAACAGCTATTATGGGTATTATGGGT', 'cut': 17, 'end_type': 'sticky', 'overhang': 17},
    'PI-SceI': {'sequence': 'ATCTATGTCGGGTGCGGAGAAAGAGGTAATGAAATGG', 'cut': 15, 'end_type': 'sticky', 'overhang': 26},
    'PleI': {'sequence': 'GAGTCNNNNN', 'cut': 9, 'end_type': 'sticky', 'overhang': 0},
    'PluTI': {'sequence': 'GGCGCC', 'cut': 5, 'end_type': 'sticky', 'overhang': 5},
    'PpuMI': {'sequence': 'RGGWCCY', 'cut': 2, 'end_type': 'sticky', 'overhang': 2},
    'PspGI': {'sequence': 'CCWGG', 'cut': 0, 'end_type': 'sticky', 'overhang': 0},
    'PspOMI': {'sequence': 'GGGCCC', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'PspXI': {'sequence': 'VCTCGAGB', 'cut': 2, 'end_type': 'sticky', 'overhang': 2},
    'PstI': {'sequence': 'CTGCAG', 'cut': 5, 'end_type': 'sticky', 'overhang': 5},
    'PvuI-HF': {'sequence': 'CGATCG', 'cut': 4, 'end_type': 'sticky', 'overhang': 4},
    'RsRII': {'sequence': 'CGGWCCG', 'cut': 2, 'end_type': 'sticky', 'overhang': 2},
    'SacI-HF': {'sequence': 'GAGCTC', 'cut': 5, 'end_type': 'sticky', 'overhang': 5},
    'SacII': {'sequence': 'CCGCGG', 'cut': 4, 'end_type': 'sticky', 'overhang': 4},
    'SalI': {'sequence': 'GTCGAC', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'SapI': {'sequence': 'GCTCTTCNNNN', 'cut': 8, 'end_type': 'sticky', 'overhang': 0},
    'Sau3AI': {'sequence': 'GATC', 'cut': 0, 'end_type': 'sticky', 'overhang': 0},
    'Sau96I': {'sequence': 'GGNCC', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'SbfI-HF': {'sequence': 'CCTGCAGG', 'cut': 6, 'end_type': 'sticky', 'overhang': 6},
    'ScrFI': {'sequence': 'CCNGG', 'cut': 2, 'end_type': 'sticky', 'overhang': 2},
    'SexAI': {'sequence': 'ACCWGGT', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'SfaNI': {'sequence': 'GCATCNNNNNNNNN', 'cut': 10, 'end_type': 'sticky', 'overhang': 0},
    'SfcI': {'sequence': 'CTRYAG', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'SfiI': {'sequence': 'GGCCNNNNNGGCC', 'cut': 8, 'end_type': 'sticky', 'overhang': 8},
    'SgrAI': {'sequence': 'CRCCGGYG', 'cut': 2, 'end_type': 'sticky', 'overhang': 2},
    'SmlI': {'sequence': 'CTYRAG', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'SpeI-HF': {'sequence': 'ACTAGT', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'SphI': {'sequence': 'GCATGC', 'cut': 5, 'end_type': 'sticky', 'overhang': 5},
    'StyD4I': {'sequence': 'CCNGG', 'cut': 0, 'end_type': 'sticky', 'overhang': 0},
    'StyI-HF': {'sequence': 'CCWWGG', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'SgrDI': {'sequence': 'CGTCGACG', 'cut': 2, 'end_type': 'sticky', 'overhang': 2},
    'TaqI-v2': {'sequence': 'TCGA', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'TfiI': {'sequence': 'GAWTC', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'TseI': {'sequence': 'GCWGC', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'Tsp45I': {'sequence': 'GTSAC', 'cut': 0, 'end_type': 'sticky', 'overhang': 0},
    'TspMI': {'sequence': 'CCCGGG', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'TspRI': {'sequence': 'NNCASTGNN', 'cut': 9, 'end_type': 'sticky', 'overhang': 9},
    'Tth111I': {'sequence': 'GACNNNGTC', 'cut': 4, 'end_type': 'sticky', 'overhang': 4},
    'TaiI': {'sequence': 'ACGT', 'cut': 4, 'end_type': 'sticky', 'overhang': 4},
    'TasI': {'sequence': 'AATT', 'cut': 0, 'end_type': 'sticky', 'overhang': 0},
    'TatI': {'sequence': 'WGTACW', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'TauI': {'sequence': 'GCSGC', 'cut': 4, 'end_type': 'sticky', 'overhang': 4},
    'XbaI': {'sequence': 'TCTAGA', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'XcmI': {'sequence': 'CCANNNNNNNNNTGG', 'cut': 8, 'end_type': 'sticky', 'overhang': 8},
    'XhoI': {'sequence': 'CTCGAG', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'XmaI': {'sequence': 'CCCGGG', 'cut': 1, 'end_type': 'sticky', 'overhang': 1},
    'AfeI': {'sequence': 'AGCGCT', 'cut': 3, 'end_type': 'blunt'},
    'AleI-v2': {'sequence': 'CACNNNNGTG', 'cut': 5, 'end_type': 'blunt'},
    'AluI': {'sequence': 'AGCT', 'cut': 2, 'end_type': 'blunt'},
    'AanI': {'sequence': 'TTATAA', 'cut': 3, 'end_type': 'blunt'},
    'BmgBI': {'sequence': 'CACGTC', 'cut': 3, 'end_type': 'blunt'},
    'BsaAI': {'sequence': 'YACGTR', 'cut': 3, 'end_type': 'blunt'},
    'BsaBI': {'sequence': 'GATNNNNATC', 'cut': 5, 'end_type': 'blunt'},
    'BsrBI': {'sequence': 'CCGCTC', 'cut': 3, 'end_type': 'blunt'},
    'BstUI': {'sequence': 'CGCG', 'cut': 2, 'end_type': 'blunt'},
    'BstZ17I-HF': {'sequence': 'GTATAC', 'cut': 3, 'end_type': 'blunt'},
    'Cac8I': {'sequence': 'GCNNGC', 'cut': 3, 'end_type': 'blunt'},
    'CviKI-1': {'sequence': 'RGCY', 'cut': 2, 'end_type': 'blunt'},
    'DraI': {'sequence': 'TTTAAA', 'cut': 3, 'end_type': 'blunt'},
    'DpnI': {'sequence': 'GAAAAAATTTTTTC', 'cut': 7, 'end_type': 'blunt'},
    'Eco53kI': {'sequence': 'GAGCTC', 'cut': 3, 'end_type': 'blunt'},
    'EcoRV': {'sequence': 'GATATC', 'cut': 3, 'end_type': 'blunt'},
    'Ecl136II': {'sequence': 'GAGCTC', 'cut': 3, 'end_type': 'blunt'},
    'Eco72I': {'sequence': 'CACGTG', 'cut': 3, 'end_type': 'blunt'},
    'Eco105I': {'sequence': 'TACGTA', 'cut': 3, 'end_type': 'blunt'},
    'Eco147I': {'sequence': 'AGGCCT', 'cut': 3, 'end_type': 'blunt'},
    'EheI': {'sequence': 'GGCGCC', 'cut': 3, 'end_type': 'blunt'},
    'FspAI': {'sequence': 'RTGCGCAY', 'cut': 4, 'end_type': 'blunt'},
    'FspI': {'sequence': 'TGCGCA', 'cut': 3, 'end_type': 'blunt'},
    'HaeIII': {'sequence': 'GGCC', 'cut': 2, 'end_type': 'blunt'},
    'HincII': {'sequence': 'GTYRAC', 'cut': 3, 'end_type': 'blunt'},
    'HpaI': {'sequence': 'GTTAAC', 'cut': 3, 'end_type': 'blunt'},
    'Hpy166II': {'sequence': 'GTNNAC', 'cut': 3, 'end_type': 'blunt'},
    'HpyCH4VI': {'sequence': 'TGCA', 'cut': 2, 'end_type': 'blunt'},
    'Hpy8I': {'sequence': 'GTNNAC', 'cut': 3, 'end_type': 'blunt'},
    'MlyI': {'sequence': 'GAGTCNNNNN', 'cut': 10, 'end_type': 'blunt'},
    'MscI': {'sequence': 'TGGCCA', 'cut': 3, 'end_type': 'blunt'},
    'MslI': {'sequence': 'CAYNNNNRTG', 'cut': 5, 'end_type': 'blunt'},
    'MspA1I': {'sequence': 'CMGCKG', 'cut': 3, 'end_type': 'blunt'},
    'MssI': {'sequence': 'GTTTAAAC', 'cut': 4, 'end_type': 'blunt'},
    'NaeI': {'sequence': 'GCCGGC', 'cut': 3, 'end_type': 'blunt'},
    'NlaIV': {'sequence': 'GGNNCC', 'cut': 3, 'end_type': 'blunt'},
    'NruI-HF': {'sequence': 'TCGCGA', 'cut': 3, 'end_type': 'blunt'},
    'PshAI': {'sequence': 'GACNNNNGTC', 'cut': 5, 'end_type': 'blunt'},
    'PsiI-v2': {'sequence': 'TTATAA', 'cut': 3, 'end_type': 'blunt'},
    'PvuII': {'sequence': 'CAGCTG', 'cut': 3, 'end_type': 'blunt'},
    'RsaI': {'sequence': 'GTAC', 'cut': 2, 'end_type': 'blunt'},
    'ScaI-HF': {'sequence': 'AGTACT', 'cut': 3, 'end_type': 'blunt'},
    'SmaI': {'sequence': 'CCCGGG', 'cut': 3, 'end_type': 'blunt'},
    'SrfI': {'sequence': 'GCCCGGGC', 'cut': 4, 'end_type': 'blunt'},
    'SspI-HF': {'sequence': 'AATATT', 'cut': 3, 'end_type': 'blunt'},
    'SwaI': {'sequence': 'ATTTAAAT', 'cut': 4, 'end_type': 'blunt'},
    'XmnI': {'sequence': 'GAANNNNTTC', 'cut': 5, 'end_type': 'blunt'},
    'ZraI': {'sequence': 'GACGTC', 'cut': 3, 'end_type': 'blunt'},
}
