name: Build Singularity/Apptainer Image

on: 
  push:
    branches:
      - '**'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v7
      - name: Install singularity
        run: |
          apt install singularity-container
      - name: Build the Image
        run: |
          make singularity
