name: Build Singularity/Apptainer Image

on: 
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v7
      - name: Install singularity
        run: |
          sudo apt install singularity-container
      - name: Build the Image
        run: |
          make sif
      # - name: Release the Image
      #   uses: actions/upload-artifact@v7
      #   with:
      #     name: rendogbs-v2.sif
      #     path: ./rendogbs-v2.sif
